trigger:
- 'main'

variables:
  repository: 'godeltech/GoogleSheetI18n'
  tag: '$(Build.BuildId)'

stages:
- stage: DockerBuild
  displayName: Build and Push image
  pool:
      vmImage: ubuntu-latest
  jobs:
  - job: Build
    displayName: Build and Push image
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'docker-hub'
        repository: '$(repository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
