trigger:
  batch: true
  branches:
    include:
    - none

pr:
  branches:
    include:
    - '*'

resources:
  repositories:
    - repository: GodelTech
      type: github
      endpoint: 'godeltech'
      name: 'GodelTech/AzureDevOps.Pipeline.Templates'
      ref: 'refs/tags/5.0.1'

extends:
  template: '.NET Core/pull-request.yml@GodelTech'
  parameters:
    buildConfiguration: 'Release'
    codeCoverageSettingsFullPath: 'CodeCoverage.runsettings'
    restoreOnlyFromNuGetFeed: true
    checkWarnings: true
    checkCoverage: true